name: authentication_sdk
description: Authentication SDK is handle all the auth service
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
dependencies: {flutter_dotenv: ^5.0.2}
