name: anime_stream_web
description: Anime Stream Web Application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  authentication_sdk:
    path: ../authentication_sdk

  bloc: ^8.0.3
  core_sdk:
    path: ../core_sdk

  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  go_router: ^4.1.0

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
